"""add_conversattions

Revision ID: 972df558e0e1
Revises: da5104ffbc40
Create Date: 2025-11-17 11:26:09.798422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '972df558e0e1'
down_revision: Union[str, Sequence[str], None] = 'da5104ffbc40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True, precision=0), server_default=sa.text('(now())::timestamp(0) with time zone'), nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True, precision=0), server_default=sa.text('(now())::timestamp(0) with time zone'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True, precision=0), server_default=sa.text('(now())::timestamp(0) with time zone'), nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True, precision=0), server_default=sa.text('(now())::timestamp(0) with time zone'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
