"""add_ebooks

Revision ID: 8d9b4c3a089e
Revises: 972df558e0e1
Create Date: 2025-12-11 19:16:31.988765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d9b4c3a089e'
down_revision: Union[str, Sequence[str], None] = '972df558e0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('collection', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True, precision=0), server_default=sa.text('(now())::timestamp(0) with time zone'), nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True, precision=0), server_default=sa.text('(now())::timestamp(0) with time zone'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('conversations', sa.Column('ebook_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_conversations_ebook_id'), 'conversations', ['ebook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_ebook_id'), table_name='conversations')
    op.drop_column('conversations', 'ebook_id')
    op.drop_table('ebooks')
    # ### end Alembic commands ###
