"""fix_ebooks_deleted

Revision ID: 9bbc6bece2f3
Revises: 8d9b4c3a089e
Create Date: 2025-12-11 19:58:52.242192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bbc6bece2f3'
down_revision: Union[str, Sequence[str], None] = '8d9b4c3a089e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ebooks', sa.Column('is_deteled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ebooks', 'is_deteled')
    # ### end Alembic commands ###
